- alias: X-Mas Tree On Before Sunset
  trigger:
    platform: sun
    event: sunset
    offset: '-01:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: light.christmas_tree_level_2_0

- alias: X-Mas Tree Off At Midnight
  trigger:
    platform: time
    after: '00:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: light.christmas_tree_level_2_0
