####################
# Configuration
####################
homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

  customize: !include customize.yaml

# Enables the frontend
frontend:

http:
  api_password: !secret http_api_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Platforms
#mqtt:
#  broker: 127.0.0.1
#  port: 1883
#  client_id: home-assistant-1
#  username: !secret mqtt_user
#  password: !secret mqtt_pass

ifttt:
  key: !secret ifttt_key

# Weather Prediction
sensor:
  platform: yr

# Text to speech
tts:
  platform: google

####################
# Sensors & Devices
####################
zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/hass/hass_venv/lib/python3.4/site-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config
  polling_interval: 30000

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

sensor 1:
  platform: cpuspeed
  name: CPU

sensor 2:
  platform: speedtest
  minute:
    - 0
    - 30
  monitored_conditions:
    - ping
    - download
    - upload

sensor 3:
  platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: processor_use

####################
# Includes
####################
group: !include groups.yaml
# script: !include scripts.yaml
automation: !include automation.yaml
