####################
# Configuration
####################
homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

  customize: !include customize.yaml

# Enables the frontend
frontend:

http:
  api_password: !secret http_api_password

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Platforms
#mqtt:
#  broker: 127.0.0.1
#  port: 1883
#  client_id: home-assistant-1
#  username: !secret mqtt_user
#  password: !secret mqtt_pass

ifttt:
  key: !secret ifttt_key

# Weather Prediction
sensor:
  platform: yr

# Text to speech
tts:
  platform: google

####################
# Sensors & Devices
####################
zwave:
  usb_path: /dev/ttyACM0
  polling_interval: 30000

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

sensor 1:
  platform: darksky
  api_key: !secret darkskyapi
  monitored_conditions:
   - summary
   - temperature
   - wind_speed
   - humidity
   - cloud_cover
   - apparent_temperature
   - precip_type
   - precip_probability
   - daily_summary
   - temperature_max
   - temperature_min

sensor 2:
  platform: cpuspeed
  name: CPU

sensor 3:
  platform: speedtest
  minute:
    - 0
    - 30
  monitored_conditions:
    - ping
    - download
    - upload

sensor 4:
  platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: processor_use

camera 1:
  name: Weather Cam
  platform: generic
  still_image_url: https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=MLB&brand=wui&num=1&delay=15&type=N0R&frame=0&scale=1.000&noclutter=0&showstorms=0&mapx=400&mapy=240&centerx=400&centery=240&transx=0&transy=0&showlabels=1&severe=0&rainsnow=0&lightning=0&smooth=0&rand=24796327&lat=0&lon=0&label=you

camera 2:
  name: I-95 at MM260
  platform: generic
  still_image_url: http://ie.trafficland.com/10201/full?system=trafficland-www&pubtoken=a89d0f0855b95b40c79ac5b0ac8f67a98c3e58b18d342e6c008468ac7d43fbdc&refreshRate=2000&cache=57338

camera 3:
  name: Beville and Clyde Morris
  platform: generic
  still_image_url: http://ie.trafficland.com/10239/full?system=trafficland-www&pubtoken=1897cde3e46d3c6273d752a080c8da1f9e5f954f70761e592f123208bfa5fce9&refreshRate=2000&cache=97561


####################
# Includes
####################
group: !include groups.yaml
# script: !include scripts.yaml
automation: !include automation.yaml
