- alias: ON Kitchen Light When Motion
  trigger:
    platform: state
    entity_id: binary_sensor.__sensor_7_0
    to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: switch.ge_12722_onoff_relay_switch_switch_6_0

- alias: OFF Kitchen Light When No Motion
  trigger:
    platform: state
    entity_id: binary_sensor.__sensor_7_0
    to: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: switch.ge_12722_onoff_relay_switch_switch_6_0
