- alias: ON Living Room Lamp Before Sunset
  trigger:
    platform: sun
    event: sunset
    offset: '-01:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: light.ge_unknown_type5044_id3031_level_4_0

- alias: ON Living Room Lamp at 5am
  trigger:
    platform: time
    after: '05:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: light.ge_unknown_type5044_id3031_level_4_0

- alias: OFF Living Room Lamp at 6:30am
  trigger:
    platform: time
    after: '06:30:00'
  action:
    service: homeassistant.turn_off
    entity_id: light.ge_unknown_type5044_id3031_level_4_0
